spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: 123456Minh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  jwtSecret: 3c472a45584f5c24554f5e44644727595a5f6730503659467443456a76
  jwtExpirationInMs: 3600000